spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    database: postgresql

  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-52-48-159-67.eu-west-1.compute.amazonaws.com:5432/d8ue8l0r5f5nhc
    username: skikegaoxlqlva
    password: 2000d9b6ecae5d3fe098ba42be536de94d8552c2427da5b6db05824417671512
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    continue-on-error: true
